<?php

namespace frontend\widgets\header;

use common\models\User;
use yii\base\Widget;
use Yii;

class  HeaderWidget extends Widget
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $model = new User();
        if (!empty(Yii::$app->user->identity->id)) {
            $userInfo = $model->getCurUserInfo();
        } else {
            $userInfo = null;
        }
        return $this->render('index', ['userInfo' => $userInfo]);

    }


}


?>