<?php

namespace frontend\models;

use common\models\User;
use frontend\models\Reply;
use Yii;


/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $article_title
 * @property string $article_intro
 * @property string $article_content
 * @property string $pub_date
 * @property integer $tag_id
 * @property integer $cate_id
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['article_id', 'user_id', 'content'], 'required'],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'article_id' => '文章id',
            'user_id' => '评论用户id',
            'content' => '评论内容',
            'date' => '评论时间',
        ];
    }


    //获取某篇文章下的评论条数
    public function getCommentsNum($articleId)
    {
        return Comment::find()->where(['article_id' => $articleId])->count();
    }

    //获取每篇文章下的评论内容
    public function getAllComments($articleId)
    {
        return Comment::find()->select(['comment.user_id','comment.id','comment.content', 'comment.date'])->with('user')->where(['article_id' => $articleId])->asArray()->all();
    }



    //获取每条评论下的回复内容
    public function getReply()
    {
        return $this->hasMany(Reply::className(), ['comment_id' => 'id'])
            ->asArray();
    }


    //评论与作者的一对一关系
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])
            ->select(['id','username','icon'])
            ->asArray();
    }

    //创建评论
    public function createComment()
    {
        //开启事务
        $transaction = Yii::$app->db->beginTransaction();
        try {
            $model = new Comment();
            $request = Yii::$app->request->post();
            $commContent = $request['commentContents'];
            $articleId = intval($request['articleId']);


            //保存评论
            $model->article_id = $articleId;
            $model->user_id = Yii::$app->user->identity->id;
            $model->content = $commContent;
            $model->date = date("Y-m-d H:i:s");
            $model->save();

            //事务成功
            if ($model->save()) {
                $transaction->commit();
                $id=$model->attributes['id'];
                $commentData=Yii::$app->db->createCommand('select comment.id, content, date, username from comment inner join user  on comment.user_id=user.id where comment.id='.$id)->queryOne();
                $commentCount=$model->getCommentsNum($articleId);
                $commentInfo['data']=$commentData;
                $commentInfo['count']=$commentCount;
                return $commentInfo;
            }
        } catch (\Exception $e) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('error',$e->getMessage());
            return false;
        }

    }

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
