<?php

namespace frontend\models;

use common\models\User;
use Yii;


/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $article_title
 * @property string $article_intro
 * @property string $article_content
 * @property string $pub_date
 * @property integer $tag_id
 * @property integer $cate_id
 */
class Reply extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reply';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'user_id', 'content'], 'required'],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'comment_id' => '评论id',
            'reply_id' => '回复id',
            'user_id' => '回复用户id',
            'content' => '回复内容',
            'date' => '回复时间',
        ];
    }


    //获取某条评论下的回复条数
    public function getReplyNum($commentId)
    {
        return Reply::find()->where(['comment_id' => $commentId])->count();
    }

    //获取每条评论下的所有回复内容
    public function getAllReply($commentId)
    {
        return  Reply::find()->select(['reply.id','reply.user_id','comment_id','content', 'date'])->with('user')->where(['comment_id' => $commentId])->asArray()->all();
    }


    //根据主键获取某条回复的相关信息
    public function getReplyByKey($id)
    {
        return Reply::find()->select(['reply.id','user_id','content', 'date'])->joinWith('user')->where(['reply.id'=>$id])->asArray()->all();
    }



    //获取回复者的信息
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])
            ->select(['id','username','icon'])
            ->asArray();
    }

    //创建评论
    public function createReply()
    {
        //开启事务
        $transaction = Yii::$app->db->beginTransaction();
        try {
            $model = new reply();
            $request = Yii::$app->request->post();
            $replyContent = $request['replyContents'];
            $commentId = intval($request['commentId']);
            $replyId =intval($request['replyId']);

            $data['a']=$replyContent;
            $data['b']=commentId;
            $data['n']=$replyId;
            
            return $data;
            //保存评论
//             $model->comment_id = $commentId;
//             $model->reply_id = replyId;            
//             $model->user_id = Yii::$app->user->identity->id;
//             $model->content = $replyContent;
//             $model->date = date("Y-m-d H:i:s");
//             $model->save();

//             //事务成功
//             if ($model->save()) {
//                 $transaction->commit();
//                 $id=$model->attributes['id'];
// //                $commentData=Yii::$app->db->createCommand("select reply.id , content, date, username from reply inner join user  on reply.user_id=user.id where reply.id=".$id)->queryOne();
//                 $commentData=$model->getReplyByKey($id);
//                 $commentCount=$model->getReplyNum($commentId);
//                 $commentInfo['data']=$commentData;
//                 $commentInfo['count']=$commentCount;
//                 return $commentInfo;
//             }
        } catch (\Exception $e) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('error',$e->getMessage());
            echo "回复失败!";
        }

    }

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
